### ISSUE TITLE
doesn't currently build

### ISSUE THREAD

**Issue by joelstransky** [MonzterDev/Roblox-TS-Template#1]
Checked out, ran `pnpm i` then `pnpm build` and it said that `"jsxFactory"` must be `"Roact.createElement",`
Changed that but it produced a `cannot find Roact` error so I ran `pnpm add -D @rbxts/roact` and imported it into each .tsx.
Now it reports
```
Roblox-TS-Template\node_modules\.pnpm\roblox-ts@2.3.0\node_modules\roblox-ts\out\Shared\util\assert.js:7
        throw new Error(`Assertion Failed! ${message !== null && message !== void 0 ? message : ""}` +
              ^

Error: Assertion Failed!
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
```

**Comment by MonzterDev** [comment]
Hey, just to be sure...when you were solving the `jsxFactory` issue, did you follow these steps? https://www.npmjs.com/package/@rbxts/react-roblox#-troubleshooting

**Comment by OverHash** [comment]
@joelstransky you likely need to uninstall `@rbxts/roact` and create a `.npmrc` file at the project root with the contents
```
node-linker=hoisted
```
(see [@rbxts/react](https://www.npmjs.com/package/@rbxts/react) installation guide).

Note: this repository does not use `@rbxts/roact`, which is now deprecated. This repository uses the newer `@rbxts/react` and `@rbxts/react-roblox`. To use this, however, you need the `@next` version of the roblox-ts compiler. See the `@rbxts/react` docs for more info.

It is likely you will want to either (a) remove `@rbxts/roact` as a dependency, or (b) just try restart with this template after creating the `.npmrc` file and checking your `roblox-ts` compiler version.
We do in fact want the `jsxFactory` to be `React.createElement`, not `Roact.createElement`.

**Comment by joelstransky** [comment]
> Hey, just to be sure...when you were solving the `jsxFactory` issue, did you follow these steps? https://www.npmjs.com/package/@rbxts/react-roblox#-troubleshooting

Wow that worked. Thanks!
